// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using TrabajoFinalRestaurante.Domain;
using TrabajoFinalRestaurante.Domain.Entities;

namespace TrabajoFinalRestaurante.Entities;

public partial class RangoReserva
{
    public int IdRangoReserva { get; set; }

    public string Descripcion { get; set; }

    public int Cupo { get; set; }

    public virtual ICollection<Reserva> Reservas { get; set; } = new List<Reserva>();
}