// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using TrabajoFinalRestaurante.Entities;

namespace TrabajoFinalRestaurante.Domain.Entities;

public partial class Reserva
{
    public string CodReserva { get; set; }

    public string NombrePersona { get; set; }

    public string ApellidoPersona { get; set; }

    public string Dni { get; set; }

    public string Mail { get; set; }

    public string Celular { get; set; }

    public DateTime FechaReserva { get; set; }

    public int IdRangoReserva { get; set; }

    public int CantidadPersonas { get; set; }

    public DateTime? FechaAlta { get; set; }

    public DateTime? FechaModificacion { get; set; }

    public string Estado { get; set; }

    public virtual RangoReserva IdRangoReservaNavigation { get; set; }
}